---
- name: Create the VM for the Kubernetes lab
  hosts: c1_cp1
  become: true
  tasks:
   - name: Disable the swap
     ansible.builtin.command: swapoff -a
     register: swap_disabled
     changed_when: swap_disabled.rc != 0

   - name: Define k8s modules to load
     ansible.builtin.command: |
       cat <<EOF | tee /etc/modules-load.d/k8s.conf
       overlay
       br_netfilter
       EOF
     register: k8s_conf_created
     changed_when: k8s_conf_created.rc != 0

   - name: Load the k8s modules
     ansible.builtin.command: modprobe --all overlay br_netfilter
     register: k8s_modules_loaded
     changed_when: k8s_modules_loaded.rc != 0

   - name: Enable IPv4 forwarding
     ansible.builtin.command: |
       cat <<EOF | tee /etc/sysctl.d/k8s.conf
       net.ipv4.ip_forward = 1
       EOF
     register: enable_ipv4_forwarding
     changed_when: enable_ipv4_forwarding.rc != 0

   - name: Apply IPv4 forwarding changes
     ansible.builtin.command: sysctl --system
     register: ipv4_forwarding_applied
     changed_when: ipv4_forwarding_applied.rc != 0

   - name: Install containerd
     ansible.builtin.command: apt update && apt install -y containerd
     register: install_containerd
     changed_when: install_containerd.rc != 0

   - name: Configure containerd
     ansible.builtin.command: |
       mkdir -p /etc/containerd
       containerd config default | tee /etc/containerd/config.toml

       sed -i 's/SystemdCgroup = false/SystemdCgroup = true/' /etc/containerd/config.toml
       grep "SystemdCgroup = true" /etc/containerd/config.toml
     register: configure_containerd
     changed_when: configure_containerd.rc != 0

   - name: Restart containerd
     ansible.builtin.systemd_service:
      state: restarted
      name: containerd
