---
- name: Create the VM for the Kubernetes lab
  hosts: c1_cp1
  become: true
  tasks:
   - name: Disable the swap
     ansible.builtin.command: swapoff -a
     register: swap_disabled
     changed_when: swap_disabled.rc != 0

   - name: Define k8s modules to load file
     ansible.builtin.copy:
      dest: /etc/modules-load.d/k8s.conf
      content: |
       overlay
       br_netfilter
      mode: '0755'

   - name: Load the k8s modules
     ansible.builtin.command: modprobe --all overlay br_netfilter
     register: k8s_modules_loaded
     changed_when: k8s_modules_loaded.rc != 0

   - name: Enable IPv4 forwarding
     ansible.builtin.copy:
      dest: /etc/sysctl.d/k8s.conf
      content: |
       net.ipv4.ip_forward = 1
      mode: '0755'

   - name: Apply IPv4 forwarding changes
     ansible.builtin.command: sysctl --system
     register: ipv4_forwarding_applied
     changed_when: ipv4_forwarding_applied.rc != 0

   - name: Update repositories cache and install containerd
     ansible.builtin.apt:
      name: containerd
      state: present
      update_cache: true

   - name: Create containerd configuration directory
     ansible.builtin.file:
      path: /etc/containerd
      state: directory
      mode: '0755'

   - name: Create containerd configuration file
     ansible.builtin.command: containerd config default > /etc/containerd/config.toml
     register: configure_containerd
     changed_when: configure_containerd.rc != 0

   - name: Enable SystemdCgroup
     ansible.builtin.replace:
      path: /etc/containerd/config.toml
      regexp: 'SystemdCgroup = false'
      replace: 'SystemdCgroup = true'

   - name: Verify SystemdCgroup is enabled
     ansible.builtin.command: grep "SystemdCgroup = true" /etc/containerd/config.toml
     register: systemcdgroup_configured
     changed_when: systemcdgroup_configured.rc != 0

   - name: Restart containerd
     ansible.builtin.systemd_service:
      state: restarted
      name: containerd
